ci?

diff --git a/sideload-check-updates b/sideload-check-updates
--- a/sideload-check-updates
+++ b/sideload-check-updates
@@ -7,16 +7,26 @@ source sideloader-config
 deviceCheck
 
 
-[ -z $CI ] && zenity --question --width=800 --text="Update and use local versionlist? ($(date -r "/tmp/badgelist.txt" +"%Y-%m-%d %H:%M:%S")) ($(cat "/tmp/badgelist.txt" | wc -l) items)\n\n
-  If not we will use the remote one from ($(date -r "$MNTLOC/badgelist.txt" +"%Y-%m-%d %H:%M:%S")) ($(cat "$MNTLOC/badgelist.txt" | wc -l) items) and copy to local."
-if [ $? != 0 ]; then
-  [ -z $CI ] && cp $MNTLOC/badgelist.txt "/tmp/badgelist.txt"
+if [ "$(ls -A $MNTLOC/ 2>/dev/null)" ]; then
+  ok "Drive mounted at: $MNTLOC ($(ls $MNTLOC | wc -l) folders available)\n\n"
 else
-  [ -z $CI ] && sideload-updatebadges
-  echo -n ''
+  error "Cannot use this function when drive is not mounted"
+  exit 0
 fi
 
-[ ! -z $CI ] && cp $MNTLOC/badgelist.txt "/tmp/badgelist.txt"
+
+
+#[ -z $CI ] && zenity --question --width=800 --text="Update and use local versionlist? ($(date -r "/tmp/badgelist.txt" +"%Y-%m-%d %H:%M:%S")) ($(cat "/tmp/badgelist.txt" | wc -l) items)\n\n
+#  If not we will use the remote one from ($(date -r "$MNTLOC/badgelist.txt" +"%Y-%m-%d %H:%M:%S")) ($(cat "$MNTLOC/badgelist.txt" | wc -l) items) and copy to local."
+#if [ $? != 0 ]; then
+#  [ -z $CI ] && cp $MNTLOC/badgelist.txt "/tmp/badgelist.txt"
+#else
+#  [ -z $CI ] && sideload-updatebadges
+#  echo -n ''
+#fi
+
+cp $MNTLOC/badgelist.txt "/tmp/badgelist.txt"
+
 
 INSTALLEDPACKAGES="$(adb shell cmd package list packages -3 | cut -f 2 -d":")"
 
